spring:
  application:
    name: CampusFlowServer
  batch:
    job:
      enabled: false
  profiles:
    default: local #기본 실행 프로필

server:
  servlet:
    context-path: / #서버 기본 경로
    encoding:
      charset: UTF-8
      enabled: true
      force: true

app:
  api-prefix: /api/v1 #백엔드 API prefix

campusflow:
  auto-enrollment:
    pre-apply:
      scheduler:
        enabled: ${AUTO_ENROLLMENT_PRE_APPLY_SCHEDULER_ENABLED:false}
        cron: ${AUTO_ENROLLMENT_PRE_APPLY_SCHEDULER_CRON:0 0 2 * * *}
        zone: ${AUTO_ENROLLMENT_PRE_APPLY_SCHEDULER_ZONE:Asia/Seoul}
