package com.example.CampusFlowServer.domain.student.enrollment.dto;

public enum AutoEnrollmentApplyOneStatus {
    APPLIED,
    REACTIVATED,
    SKIPPED_ALREADY_ACTIVE,
    SKIPPED_WISH_COURSE_NOT_FOUND,
    SKIPPED_COURSE_OFFERING_MISMATCH,
    SKIPPED_NOT_DONE,
    SKIPPED_OVER_CAPACITY,
    SKIPPED_GRADE_RESTRICTED,
    SKIPPED_PREREQUISITE_REQUIRED,
    SKIPPED_CREDIT_LIMIT,
    SKIPPED_TIME_CONFLICT
}
